// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"fmt"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-mall/internal/conf"
	"kratos-mall/internal/data"
	"kratos-mall/internal/server"
	"kratos-mall/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}

	fmt.Println(dataData)

	wechatService := service.NewWechatService()

	// 注册http
	httpServer := server.NewHTTPServer(confServer, wechatService, logger)
	// 注册grpc
	grpcServer := server.NewGRPCServer(confServer, wechatService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
